networks:
  traefik:
    external: true

services:
  react-app:
    container_name: jakeswestcoast
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik
    labels:
      - traefik.http.routers.jwc.rule=Host(`jakeswestcoast.com`) || Host(`www.jakeswestcoast.com`)
      - traefik.http.routers.jwc.tls=true
      - traefik.http.routers.jwc.tls.certresolver=lets-encrypt
      - traefik.http.services.jwc.loadbalancer.server.port=80
